name: build-NETGEAR-BZV

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 官方支持NETGEAR-BZV的源码
        uses: actions/checkout@v4
        with:
          repository: chongshengB/padavan-4.4
          ref: master
          fetch-depth: 0

      - name: 安装完整依赖
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake flex bison gawk git libtool-bin gperf python3-docutils autopoint gettext ccache zlib1g-dev libssl-dev libncurses5-dev unzip zip liblzma-dev liblzo2-dev libbz2-dev libelf-dev lib32gcc-s1 lib32stdc++6

      - name: 开始编译固件
        run: |
          make NETGEAR-BZV TOOLCHAIN=mipsel-linux-musl V=99

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: NETGEAR-BZV-固件
          path: trunk/images/*.chk
