name: build-NETGEAR-BZV

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [NETGEAR-BZV]
        toolchain: [mipsel-linux-musl]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: false

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential cmake flex bison gawk git \
          libtool-bin gperf python3-docutils autopoint gettext ccache \
          zlib1g-dev libssl-dev libncurses5-dev unzip zip \
          liblzma-dev liblzo2-dev libbz2-dev libelf-dev libc6-dev squashfs-tools

      # 关键：直接编译目标，去掉不支持的 make tools 步骤
      - name: Build firmware
        run: |
          make ${{ matrix.target }} TOOLCHAIN=${{ matrix.toolchain }} V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-firmware
          path: |
            trunk/images/*.chk
            trunk/images/*.trx
            trunk/images/*.bin
          if-no-files-found: error
